/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

object App {
  def main(args: Array[String]): Unit = {
    println(greeting())
    println(greeting("test"))
  }

  def greeting(message :String = "Hello, world!"): String = message

}
